"""
Tracking Log Model

MongoDB document model for health tracking logs (BP, glucose, medication).
Each log entry stores raw readings, classifier results, and optional AI nudges.
"""

from datetime import datetime
from typing import Optional, List
from pymongo import IndexModel
from beanie import Document, Indexed
from pydantic import Field, BaseModel


class MedicationEntry(BaseModel):
    """A single medication taken/skipped record.

    Attributes:
        name: Medication name as entered by the user.
        taken: Whether the medication was taken (True) or skipped (False).
    """

    name: str
    taken: bool = False


class NudgeData(BaseModel):
    """AI-generated nudge returned by the Habit Coach agent.

    Attributes:
        text: The nudge message (2-3 sentences).
        action_type: Category of the suggested action.
        generated_at: Timestamp when the nudge was generated.
    """

    text: str
    action_type: str = "monitoring"  # diet | exercise | medication | monitoring | referral
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class TrackingLog(Document):
    """Health tracking log document model.

    Stores a single check-in entry — one of blood pressure, glucose,
    or medication adherence — along with its classifier result and an
    optional AI nudge.

    Attributes:
        user_id: Firebase UID of the logged-in user.
        log_type: Discriminator — ``"bp"`` | ``"glucose"`` | ``"medication"``.
        systolic: Systolic BP reading (mmHg). Required when log_type is ``"bp"``.
        diastolic: Diastolic BP reading (mmHg). Required when log_type is ``"bp"``.
        bp_classification: Output of ``classify_bp()`` for this reading.
        glucose_value: Blood glucose reading. Required when log_type is ``"glucose"``.
        glucose_unit: Unit of the glucose reading — ``"mmol_l"`` | ``"mg_dl"``.
        glucose_test_type: Test type — ``"random"`` | ``"fasting"``.
        glucose_classification: Output of ``classify_glucose()`` for this reading.
        medications: List of medication entries. Required when log_type is ``"medication"``.
        mood: Optional mood at check-in — ``"good"`` | ``"okay"`` | ``"bad"``.
        notes: Optional free-text notes from the user.
        timestamp: When this check-in was recorded.
        nudge: Optional AI nudge generated by the Habit Coach agent.
    """

    user_id: Indexed(str) #type: ignore[valid-type]  # Firebase UID
    patient_id: Optional[str] = None ## Patient ID — None for self-tracked logs

    log_type: str  # "bp" | "glucose" | "medication"

    # BP-specific fields 
    systolic: Optional[int] = None
    diastolic: Optional[int] = None
    bp_classification: Optional[dict] = None

    # Glucose-specific fields 
    glucose_value: Optional[float] = None
    glucose_unit: Optional[str] = None  # "mmol_l" | "mg_dl"
    glucose_test_type: Optional[str] = None  # "random" | "fasting"
    glucose_classification: Optional[dict] = None

    # Medication-specific fields 
    medications: Optional[List[MedicationEntry]] = None

    # Common fields 
    mood: Optional[str] = None  # "good" | "okay" | "bad"
    notes: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # AI response 
    nudge: Optional[NudgeData] = None

    class Settings:
        name = "tracking_logs"
        indexes = [
            IndexModel([("user_id", 1), ("timestamp", -1)]),
            IndexModel([("patient_id", 1), ("timestamp", -1)], sparse=True),
            IndexModel([("user_id", 1), ("log_type", 1), ("timestamp", -1)]),
            IndexModel([("patient_id", 1), ("log_type", 1), ("timestamp", -1)], sparse=True),
        ]
